// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayzevbiczfjizqiyckai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5emV2YmljemZqaXpxaXlja2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTAyNjMsImV4cCI6MjA2MTc4NjI2M30.2xx0BlXDKJvqaJawxo-mdu6oZjp_JMSd5cu_qQWJpRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);